#lang sicp

(define (make-account balance password)
  (define (with-draw amount)
    (if (>= balance amount)
        (begin (set! balance (- balance amount))
              balance)
        (error "Insufficient funds")))
  (define (deposit amount)
    (set! balance (+ balance amount))
    balance)
  (define (correct-password? given-password)
    (eq? given-password password))
  (define (wrong-password amount)
      (display "Incorrect password")
      (newline))
  (define (dispatch user-input-pass m)
    (if (correct-password? user-input-pass)
      (cond ((eq? m 'with-draw) with-draw)
            ((eq? m 'deposit) deposit)
            (else (error "Unknown request -- MAKE-ACCOUNT" m)))
      wrong-password))
  dispatch)

(define (make-joint account origin-pass new-pass)
  (lambda (user-input-pass m)
    (if (eq? user-input-pass new-pass)
        (account origin-pass m)
        (lambda (amount)
          (display "Incorrect password")
          (newline)))))
        
(define peter-acc (make-account 100 'secret-password))
(define pual-acc (make-joint peter-acc 'secret-password 'rosebud))
((pual-acc 'rosebud 'with-draw) 40)
((peter-acc 'secret-password 'with-draw) 40)
((pual-acc 'secret-password 'with-draw) 10)